option casemap :none
include \masm32\include\masm32rt.inc
includelib \masm32\lib\masm32.lib
printf PROTO C :VARARG

.DATA
_new_line_ DB 13, 10, 0
_format_long DB "%d", 13, 10, 0
_format_dfloat DB "%.20Lf", 13, 10, 0
_format_string DB "%s", 13, 10, 0
_MSG_ERROR_DIV_CERO DB "ERROR EN TIEMPO DE EJECUCION: Division por cero.", 0
_MSG_ERROR_DIV_CERO_FLOAT DB "ERROR EN TIEMPO DE EJECUCION: Division por cero (flotante).", 0
_MSG_ERROR_OVERFLOW_PROD DB "ERROR EN TIEMPO DE EJECUCION: Overflow en producto de enteros.", 0
_MSG_ERROR_RECURSION DB "ERROR EN TIEMPO DE EJECUCION: Recursion no permitida.", 0
_aux_long DD ?
_aux_dfloat DQ ?

; --- Variables y Constantes del Programa ---
_P_LE_PROGRAMA_FUNCION_COMPLETA DQ ?
_D_CONVERTIDO_PROGRAMA DQ ?
_VAR_GLOBAL_D_PROGRAMA DQ ?
_L2_PROGRAMA DD ?
_VAR_INFERIDA_PROGRAMA DD ?
_ARG_L_PROGRAMA_LAMBDA DQ ?
_P_SL_PROGRAMA_FUNCION_COMPLETA DD ?
_VAR_GLOBAL_PROGRAMA DD ?
_L_PARA_CONVERTIR_PROGRAMA DD ?
_Retorno_Long_de_funcion_ DB "Retorno Long de funcion:", 0
_RET_D_PROGRAMA DQ ?
_Probando_Lambda___ DB "Probando Lambda...", 0
_Retorno_DFloat_de_funcion_ DB "Retorno DFloat de funcion:", 0
_0_0 DQ 0.0
_1_0 DQ 1.0
_RET_L_PROGRAMA DD ?
_2_0 DQ 2.0
_1_5 DQ 1.5
_SUMA_PROGRAMA_FUNCION_COMPLETA DQ ?
_L1_PROGRAMA DD ?
_VAR_LAMBDA_PROGRAMA DQ ?
_IN_FUNC__FUNCION_COMPLETA_PROGRAMA DB 0
_RET_0__FUNCION_COMPLETA_PROGRAMA DD ?
_RET_1__FUNCION_COMPLETA_PROGRAMA DQ ?
; --- Fin Variables y Constantes ---


.CODE

; --- Definicion de Funcion: FUNCION%COMPLETA ---
_FUNCION_COMPLETA_PROGRAMA PROC
push ebp
mov ebp, esp
push edi
push esi
FLD _P_LE_PROGRAMA_FUNCION_COMPLETA
FILD _P_SL_PROGRAMA_FUNCION_COMPLETA
FADD
FSTP _aux_dfloat
FLD _aux_dfloat
FSTP _SUMA_PROGRAMA_FUNCION_COMPLETA
FLD _SUMA_PROGRAMA_FUNCION_COMPLETA
FSTP _P_LE_PROGRAMA_FUNCION_COMPLETA
MOV EAX, _P_SL_PROGRAMA_FUNCION_COMPLETA
IMUL EAX, 2
JO _ERROR_OVERFLOW_PROD
MOV _aux_long, EAX
MOV EAX, _aux_long
MOV _VAR_GLOBAL_PROGRAMA, EAX
MOV EAX, _VAR_GLOBAL_PROGRAMA
MOV _RET_0__FUNCION_COMPLETA_PROGRAMA, EAX
FLD _P_LE_PROGRAMA_FUNCION_COMPLETA
FSTP _RET_1__FUNCION_COMPLETA_PROGRAMA
JMP _FUNCION_COMPLETA_PROGRAMA_exit
_FUNCION_COMPLETA_PROGRAMA_exit:
pop esi
pop edi
mov esp, ebp
pop ebp
RET
_FUNCION_COMPLETA_PROGRAMA ENDP
; --- Fin de Funcion: FUNCION%COMPLETA ---

START:
FINIT
MOV EAX, 10
MOV _VAR_INFERIDA_PROGRAMA, EAX
MOV EAX, 0
MOV _VAR_GLOBAL_PROGRAMA, EAX
FLD _0_0
FSTP _VAR_GLOBAL_D_PROGRAMA
MOV EAX, 100
MOV _L1_PROGRAMA, EAX
MOV EAX, 200
MOV _L2_PROGRAMA, EAX
_label0:
MOV EAX, _VAR_INFERIDA_PROGRAMA
ADD EAX, 1
MOV _aux_long, EAX
MOV EAX, _aux_long
MOV _VAR_INFERIDA_PROGRAMA, EAX
invoke printf, ADDR _format_long, _VAR_INFERIDA_PROGRAMA
MOV EAX, _VAR_INFERIDA_PROGRAMA
CMP EAX, 12
JL _label0
; Chequeo de recursion (h)
CMP _IN_FUNC__FUNCION_COMPLETA_PROGRAMA, 1
JE _ERROR_RECURSION
MOV _IN_FUNC__FUNCION_COMPLETA_PROGRAMA, 1
MOV EAX, _L1_PROGRAMA
MOV _P_SL_PROGRAMA_FUNCION_COMPLETA, EAX
FLD _1_5
FSTP _P_LE_PROGRAMA_FUNCION_COMPLETA
CALL _FUNCION_COMPLETA_PROGRAMA
MOV _IN_FUNC__FUNCION_COMPLETA_PROGRAMA, 0
MOV EAX, _RET_0__FUNCION_COMPLETA_PROGRAMA
MOV _aux_long, EAX
MOV EAX, _RET_0__FUNCION_COMPLETA_PROGRAMA
MOV _RET_L_PROGRAMA, EAX
FLD _RET_1__FUNCION_COMPLETA_PROGRAMA
FSTP _RET_D_PROGRAMA
invoke printf, ADDR _format_string, ADDR _Retorno_Long_de_funcion_
invoke printf, ADDR _format_long, _RET_L_PROGRAMA
invoke printf, ADDR _format_string, ADDR _Retorno_DFloat_de_funcion_
invoke printf, ADDR _format_dfloat, _RET_D_PROGRAMA
invoke printf, ADDR _format_string, ADDR _Probando_Lambda___
FLD _1_0
FSTP _VAR_LAMBDA_PROGRAMA
FLD _RET_D_PROGRAMA
FSTP _ARG_L_PROGRAMA_LAMBDA
FLD _ARG_L_PROGRAMA_LAMBDA
FLD _2_0
FTST
FSTSW AX
SAHF
JE _ERROR_DIV_CERO_FLOAT
FDIVR
FSTP _aux_dfloat
FLD _aux_dfloat
FSTP _VAR_LAMBDA_PROGRAMA
invoke printf, ADDR _format_dfloat, _VAR_LAMBDA_PROGRAMA
MOV EAX, 0
SUB EAX, 10
MOV _aux_long, EAX
MOV EAX, _aux_long
MOV _L_PARA_CONVERTIR_PROGRAMA, EAX
FILD _L_PARA_CONVERTIR_PROGRAMA
FSTP _D_CONVERTIDO_PROGRAMA
invoke printf, ADDR _format_dfloat, _D_CONVERTIDO_PROGRAMA

; --- Fin del programa principal ---
invoke ExitProcess, 0


; --- Rutinas de Error en Tiempo de Ejecucion ---
_ERROR_DIV_CERO:
invoke printf, ADDR _MSG_ERROR_DIV_CERO
invoke ExitProcess, 1
_ERROR_DIV_CERO_FLOAT:
invoke printf, ADDR _MSG_ERROR_DIV_CERO_FLOAT
invoke ExitProcess, 1
_ERROR_OVERFLOW_PROD:
invoke printf, ADDR _MSG_ERROR_OVERFLOW_PROD
invoke ExitProcess, 1
_ERROR_RECURSION:
invoke printf, ADDR _MSG_ERROR_RECURSION
invoke ExitProcess, 1

END START
